### ISSUE TITLE
RSS 'WhoDidIt Feed for BBOX' option to load webpage with filters

### ISSUE THREAD

**Issue by DaveF63** [simon04/whodidit#11]
Hi
The 'WhoDidIt Feed for BBOX..' option on the RSS feed opens thewebpage without applying the user filter & defaults 'age' to a week. Is it possible to get it to apply user filters?

Cheers
Dave F.

**Comment by simon04** [comment]
* User filtering: enter a user name in the text box, click "Apply", click "Get RSS link"
* Age filtering: is not implemented, but the RSS feed outputs the most recent 20 edits
