### ISSUE TITLE
non-rectangular BBOX

### ISSUE THREAD

**Issue by DaveF63** [simon04/whodidit#12]
There appears to be an option to draw non-rectangular BBOX. How is that achieved?

Thanks

**Comment by simon04** [comment]
Non-rectangular BBOX can be specified for RSS only. See `wkt` on the usage page http://simon04.dev.openstreetmap.org/whodidit/scripts/rss.php

**Comment by TZornG** [comment]
Is this still supported? The output lists a couple of error messages and is no valid RSS feed, though the content is transported.
