### ISSUE TITLE
Change not displayed

### ISSUE THREAD

**Issue by Archibalde** [simon04/whodidit#16]
Hi,

I was wondering, why [this changset](http://www.openstreetmap.org/changeset/33129106) is not displayed either on the map ( http://simon04.dev.openstreetmap.org/whodidit/index.html?lat=46.37&lon=6.53&zoom=12 ) or in my RSS feed ( http://simon04.dev.openstreetmap.org/whodidit/scripts/rss.php?bbox=6.398507,46.333269,6.617891,46.41144 ) ?

Regards,

Archibalde

**Comment by simon04** [comment]
This is a known limitation, see #1.

**Comment by Archibalde** [comment]
Thanks for your answer, and sorry for the duplicate.
