### ISSUE TITLE
Filter by not-user

### ISSUE THREAD

**Issue by JBacc1** [simon04/whodidit#17]
Hello,
I think filtering by excluding a contributor would be more usefull than filtering for a contributor. The idea is of finding who else edited around an area, so everyone is important but me.

**Comment by simon04** [comment]
This is already possible (since b7de2725f211b9b4eba5086086dc411f4fc15251). Use `-username` or `!username`. See the tooltip text.

**Comment by ivanbranco** [comment]
Could be a good idea to explain the "exclude syntax" here: https://simon04.dev.openstreetmap.org/whodidit/wdi_guide.gif
