### ISSUE TITLE
Make the RSS feed usable in IFTTT again

### ISSUE THREAD

**Issue by mikini** [simon04/whodidit#19]
I have been using ifttt.com and RSS feeds from whodidit for keeping track of changes in areas of interest to me.

However it seems IFTTT has changed their requirements for RSS feeds sometime in October because it doesn't work any more and the site complains about feed error. Looking into the [requirements](https://ifttt.com/help/troubleshooting-services#rss-feed-not-working) they expect a GUID for each feed item.

This is also what the W3C validator suggest when [validating the actual feed](http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fsimon04.dev.openstreetmap.org%2Fwhodidit%2Fscripts%2Frss.php%3Fbbox%3D8.539598%2C55.431508%2C8.631436%2C55.493016):
"This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations."

As I understand it after a little [doc](http://validator.w3.org/feed/docs/warning/MissingGuid.html) [reading](http://www.rssboard.org/rss-specification#ltguidgtSubelementOfLtitemgt), the GUID in this situation should/could be identical to the item's link entry which is a link directly to the OSM CS.

I'm, however, considering to migrate to [something open](http://alternativeto.net/software/ifttt/?license=opensource) instead, after reading [this](https://blog.pinboard.in/2016/03/my_heroic_and_lazy_stand_against_ifttt/) about ifttt's business methods.

**Comment by simon04** [comment]
Thanks for the detailed report. The issue should be fixed now.
