### ISSUE TITLE
Filter by not-changeset

### ISSUE THREAD

**Issue by JBosm** [simon04/whodidit#23]
Hello,
I saw https://github.com/simon04/whodidit/issues/17 for filtering out a user, but could not do the same with a changeset. Is it available and I could not find how (I tried -#changeset)? If not, would it be hard to implement?

**Comment by simon04** [comment]
Now, multiple (negated) changeset ids are supported, e.g., `123,456` or `!123,!456` (analogously to the usernames). Have fun! :smile:
