### ISSUE TITLE
Incorrect links to user profiles space in their login

### ISSUE THREAD

**Issue by Self-Perfection** [simon04/whodidit#25]
Let's take for instance this changeset
https://www.openstreetmap.org/changeset/54128596

RSS feed with this changeset as a link to user profile provides
https://www.openstreetmap.org/user/Елизавета+Кружкова

One have to manually replace "+" in URL with " " to get to profile page.

**Comment by simon04** [comment]
Thanks for the report. The user links should be working now, e.g. http://simon04.dev.openstreetmap.org/whodidit/scripts/rss.php?bbox=37.453333,55.854692,37.485863,55.871129
