### ISSUE TITLE
No more updates since a few days

### ISSUE THREAD

**Issue by mmd-osm** [simon04/whodidit#26]
Some users in the German forum reported that the site doesn't work since a few days, e.g. no more updates are shown. Could this be related to the recent switch to https? https://github.com/openstreetmap/operations/issues/190

I'm getting some mixed content errors, maybe there's also some other issue?
  
https://forum.openstreetmap.org/viewtopic.php?pid=679923

**Comment by simon04** [comment]
Thanks for reporting. Indeed, some JavaScript files had been fetched via HTTP and therefore not been executed.
