### ISSUE TITLE
w3 feed validator and Thunderbird complain about invalid feed

### ISSUE THREAD

**Issue by TZornG** [simon04/whodidit#27]
Trying to add a feed URL to Thunderbird the URL gets rejected as invalid referring to [w3c feed validator](http://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fsimon04.dev.openstreetmap.org%2Fwhodidit%2Fscripts%2Frss.php%3Fbbox%3D8.160157%2C49.994825%2C8.37954%2C50.121344):

> Sorry
> 
> This feed does not validate.
> line 6, column 54: link must be a full and valid URL: /whodidit/?lat=50.055&lon=8.265&zoom=12 
> 
>         	<link>/whodidit/?lat=50.055&amp;lon=8.265&amp;zoom=12</link>

**Comment by simon04** [comment]
Thanks for reporting. This issue should be fixed now :smile:
