### ISSUE TITLE
Service is not available

### ISSUE THREAD

**Issue by dbf256** [simon04/whodidit#33]
Requests to https://simon04.dev.openstreetmap.org/whodidit/scripts/tiles.php?age=7&bbox=...
fails with 

Service Unavailable
The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.
Apache/2.4.29 (Ubuntu) Server at simon04.dev.openstreetmap.org Port 443

or

Gateway Timeout
The gateway did not receive a timely response from the upstream server or application.
Apache/2.4.29 (Ubuntu) Server at simon04.dev.openstreetmap.org Port 443

**Comment by simon04** [comment]
Cannot reproduce:

```
$ curl --head https://simon04.dev.openstreetmap.org/whodidit/
HTTP/2 200
...

$ curl https://simon04.dev.openstreetmap.org/whodidit/scripts/tiles.php
{ "error" : "BBox required" }
```

**Comment by dbf256** [comment]
Maybe it depends on time of day/etc?
Because with curl I have

```
~$ curl https://simon04.dev.openstreetmap.org/whodidit/scripts/tiles.php?age=7\&bbox=39.890580427954,57.61823491931,39.914012205908,57.622484923726
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at simon04.dev.openstreetmap.org Port 443</address>
</body></html>
```

I think you should be able to see such request in Apache logs?
