### ISSUE TITLE
No newer edits after the 18th of January 2019

### ISSUE THREAD

**Issue by lgiard** [simon04/whodidit#34]
Hi, 

I'm no longer seeing any newer changeset after the 18th of January 2019. Is there a bug/error on the server preventing it to show newer edits ? 

Regards,

**Comment by hugobqd** [comment]
The world will fall into chaos !

**Comment by jidanni** [comment]
I see new edits.

**Comment by simon04** [comment]
Fixed, see https://github.com/simon04/whodidit/issues/49#issuecomment-751392318.
