### ISSUE TITLE
RSS down?

### ISSUE THREAD

**Issue by skfd** [simon04/whodidit#41]
Hi, Simon! Love this tool! But looks like it's down for me, all RSS links give me 503 error. Front page work OK.

https://simon04.dev.openstreetmap.org/whodidit/scripts/rss.php?bbox=30.23538,50.338127,30.739378,50.536024

**Comment by daganzdaanda** [comment]
Hi, I can confirm this - my RSSs haven't updated for about a week. Hope you can jump start the service again ;-)
BTW, Zveriks version is also not working, but I don't know since when.

**Comment by daganzdaanda** [comment]
@simon04 My feeds have updated again today -- thanks for fixing it!

**Comment by cliffordsnow** [comment]
Is the RSS service down again?

**Comment by momu** [comment]
Seems so. Here last update was on 18th.

**Comment by amadvance** [comment]
RSS is returning this error: Uncaught Error: Call to a member function fetch_assoc() on bool in /home/simon04/whodidit_prod/scripts/rss.php:62


```
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
        <title>WhoDidIt Feed for BBOX [9.44,45.74,9.64,45.89]</title>
        <description>WhoDidIt feed for BBOX [9.44,45.74,9.64,45.89]</description>
        <link>https://simon04.dev.openstreetmap.org/whodidit/?lat=45.81&amp;lon=9.535&amp;zoom=12</link>
        <generator>WhoDidIt</generator>
        <ttl>60</ttl>
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function fetch_assoc() on bool in /home/simon04/whodidit_prod/scripts/rss.php:62
Stack trace:
#0 {main}
  thrown in <b>/home/simon04/whodidit_prod/scripts/rss.php</b> on line <b>62</b><br />
```

**Comment by simon04** [comment]
Fixed, see https://github.com/simon04/whodidit/issues/49#issuecomment-751392318.
