### ISSUE TITLE
You have an error in your SQL syntax

### ISSUE THREAD

**Issue by JulienPalard** [simon04/whodidit#46]
Was trying to survey my city, I got no tiles, so I checked network response and spotted:

    You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(GeomFromText('POLYGON((4890 216, 4891 216, 4891 219, 4890 219, 4890 216))'), la' at line 1

Please notice it's my very first use of whodidit, I may have done something "unexpected".

**Comment by kaligrafy** [comment]
Same problem here
