### ISSUE TITLE
2020: Everything is broken!

### ISSUE THREAD

**Issue by simon04** [simon04/whodidit#49]
Due to a server upgrade to Ubuntu 20.04, plenty of problems and incompatibilities arose:

- [x] MySQL: old tables cannot be queried/inserted anymore – dropped and recreating, reindexing starting with 2020-11-01
- [x] MySQL 8: invalid syntax – #50
- [x] MySQL 8: spatial index is not used without SRS – e39389c733d844d0e3afd65d143f352bac6c8e7f
- [x] Perl upgrade: missing modules, missing local::lib
- [x] Perl: parse_osc.pl is slow – #51
- [x] Is this project still relevant?
- [ ] Is dev.osm.org the right place to host this project?

Relates to: https://github.com/simon04/whodidit/issues/41, https://github.com/simon04/whodidit/issues/46, https://github.com/simon04/whodidit/issues/47, https://github.com/simon04/whodidit/issues/48

**Comment by ZLima12** [comment]
I would say this project is still relevant, for me at least.

**Comment by EvansMike** [comment]
I use it, but now I host it locally and limit data wget to the bounding box of the area that interests me.  I guess this just needs to relocate to a server somewhere that has enough space and bandwidth.  The code still works fine.

**Comment by Heriogi** [comment]
It is a great pity that it no longer works.

**Comment by Frankthetankk** [comment]
The sample website no longer works. I use this site often. How can we fix this?

**Comment by loser2k1** [comment]
Dear @simon04, is it by any chance possible to revive the https://simon04.dev.openstreetmap.org/whodidit/ website of yours?
I see 13 people here who would love to have it back. ;)

**Comment by Marc-marc-marc** [comment]
witch os/version allow the current code to work ? for ex what was the os version before the update to ubunto 20.04 ? ubuntu 18.04 ?

**Comment by osm-spiregrain** [comment]
For those of you who just can't wait for this to be resolved; you can try the similar system on osmcha.org.   

You can create an account, then create a filter (setting an area, and changes you want to look out for).   Each saved filter has an RSS feed associated.

**Comment by daviddelon** [comment]
> For those of you who just can't wait for this to be resolved; you can try the similar system on osmcha.org.

Thanks but Osmcha is not equivalent: it displays all the changesets containing the area to survey, and the resulting feed is cluttered with worldwide change. For example, if you survey an area in the south of France, you get all the changesets with changes, in the same changeset, concerning Russia and Brasil, and it's a lot.

**Comment by osm-spiregrain** [comment]
@daviddelon - You correct that the OSMCha is not directly equivalent.   But I have found that by setting the "BBox size bound" filter option to something like 3 or 4, changesets covering a very large area (compared with your area of interest) are excluded.   That might help.

**Comment by daviddelon** [comment]
@osm-spiregrain : excellent ! Thanks for this tip.

**Comment by Sowa1980** [comment]
Тоже хотел бы видеть работоспособный сайт, очень выручал не однократно! Востановите, если это возможно, за ранее спасибо!

**Comment by osm-spiregrain** [comment]
Everything is fixed! (?)   My Whodidit feed sprang back to life this morning....

**Comment by jonpsp** [comment]
I'm not seeing any change tiles on the web site.  I don't use the RSS feed.

**Comment by jonpsp** [comment]
Some change tiles have appeared in my view (https://simon04.dev.openstreetmap.org/whodidit/?zoom=12&lat=51.32595&lon=-0.83002&layers=B&age=2).  I find whodidit much more useful than the equivalent from Pascal Neis (https://resultmaps.neis-one.org/osm-change-tiles#13/51.3927/-0.6221).

**Comment by simon04** [comment]
I've rewritten the data ingestion process in Go (#51).
I've ingested all changes starting with 2020-11-01.
I've fixed the broken spatial index due to the MySQL 8 update (e39389c).

whodidit should be operational again – Merry Chrismas! :christmas_tree:

**Comment by Heriogi** [comment]
Hi simon04,
thank you for making it work again. A very helpful thing.
Happy New Year

**Comment by amadvance** [comment]
Thanks for the wonderful Christmas present!
