### ISSUE TITLE
Missing changesets, that have NOT  been closed at upload but left open

### ISSUE THREAD

**Issue by hungerburg** [simon04/whodidit#55]
My changesets are missing :( I guess I found out why - It is because I leave them open for one hour, so I can do some hotfixes after looking at an analyzer.

The osc parser perl skript should get them still, from reading the source and the osc -- is it not used on the live site?

**Comment by simon04** [comment]
Thanks for reporting. Hopefully, the issue is addressed via d9aab82. The Perl script is no longer used in production and has been replaced with a Go program, see https://github.com/simon04/whodidit/pull/51.

**Comment by hungerburg** [comment]
Hallo Simon, just did an edit "Klinik survey" and after a minute or so, it shows up :)

**Comment by simon04** [comment]
Thank you for confirming that the issue is indeed fixed :)
