### ISSUE TITLE
Website not working for a while

### ISSUE THREAD

**Issue by jonpsp** [simon04/whodidit#57]
Over the past couple of weeks, the [website](https://simon04.dev.openstreetmap.org/whodidit) ([example](https://simon04.dev.openstreetmap.org/whodidit/?zoom=12&lat=51.35062&lon=-0.8362&layers=BTT&age=16%20hour&user=!jpennycook)) has mostly been down.  When it does work, often the map is displayed but no changes are visible.  Today I get `ERR_CONNECTION _REFUSED` in Chrome.

The address resolves to 193.60.236.13 which itself has a PTR record pointing at `errol.openstreetmap.org`

**Comment by jonpsp** [comment]
The website worked yesterday, but now I'm getting a 403 Forbidden error

**Comment by mxxcon** [comment]
RSS feed haven't been updating in the last few days and when trying to create new RSS feed I get this error:

`<br />
<b>Fatal error</b>:  Uncaught mysqli_sql_exception: Table './simon04/wdi_tiles' is marked as crashed and last (automatic?) repair failed in /home/simon04/whodidit_prod/scripts/rss.php:49
Stack trace:
#0 /home/simon04/whodidit_prod/scripts/rss.php(49): mysqli-&gt;query()
#1 {main}
  thrown in <b>/home/simon04/whodidit_prod/scripts/rss.php</b> on line <b>49</b><br />`

**Comment by jonpsp** [comment]
Currently the map is shown, but no change tiles are displayed.

**Comment by simon04** [comment]
Somebody fixed the database. Thanks!

**Comment by asg7443** [comment]
RSS feed is broken again with the same error:

Uncaught mysqli_sql_exception: Table './simon04/wdi_tiles' is marked as crashed and last (automatic?) repair failed in /home/simon04/whodidit_prod/scripts/rss.php:49
