### ISSUE TITLE
Changesets missed from new users (UID>mediumint?)

### ISSUE THREAD

**Issue by hungerburg** [simon04/whodidit#58]
From varying accounts a user mass creates hedges and fences here. Nothing to be seen on WhoDidIt of the changesets though. Why are these edits missing?

First thought of mine was the hit and run method - the user creates an account, does his edits, then deletes the account. But even where their account remains, nothing gets shown in WhoDidIt (https://www.openstreetmap.org/user/Wetscher/history)

Here what OSMCha knows - https://osmcha.org/?filters=%7B%22geometry%22%3A%5B%7B%22label%22%3A%7B%22coordinates%22%3A%5B%5B%5B11.284376%2C47.320238%5D%2C%5B11.489097%2C47.322995%5D%2C%5B11.476895%2C47.193253%5D%2C%5B11.291154%2C47.202466%5D%2C%5B11.284376%2C47.320238%5D%5D%5D%2C%22type%22%3A%22Polygon%22%7D%2C%22value%22%3A%7B%22coordinates%22%3A%5B%5B%5B11.284376%2C47.320238%5D%2C%5B11.489097%2C47.322995%5D%2C%5B11.476895%2C47.193253%5D%2C%5B11.291154%2C47.202466%5D%2C%5B11.284376%2C47.320238%5D%5D%5D%2C%22type%22%3A%22Polygon%22%7D%7D%5D%2C%22uids%22%3A%5B%7B%22label%22%3A%2220025177%22%2C%22value%22%3A%2220025177%22%7D%2C%7B%22label%22%3A%2220024880%22%2C%22value%22%3A%2220024880%22%7D%2C%7B%22label%22%3A%2219987577%22%2C%22value%22%3A%2219987577%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%7D

**Comment by hungerburg** [comment]
Maybe it has to do with new mappers in general? E.g. https://www.openstreetmap.org/changeset/139058500 does not show neither here https://simon04.dev.openstreetmap.org/whodidit/?zoom=13&lat=46.91299&lon=14.10631&layers=BTT&age=1%20month - it certainly should, lots of nodes created.

**Comment by simon04** [comment]
Thanks for investigating and reporting. Very likely so. According to https://dev.mysql.com/doc/refman/8.0/en/integer-types.html the Maximum Value Unsigned is 16777215. And the linked user has ID 20025177.

```sql
ALTER TABLE wdi_changesets MODIFY COLUMN user_id INT UNSIGNED NOT NULL;
--- took approximately 600s
```
