### ISSUE TITLE
Whodidit does not work right now

### ISSUE THREAD

**Issue by vmicho** [simon04/whodidit#60]
At least the website doe not show anything since like a week :(
Something crashed?

**Comment by DonKult** [comment]
@asg7443 reported a while ago in a [closed issue](https://github.com/simon04/whodidit/issues/57#issuecomment-2060400664) that was about a similar problem, that the RSS feed is currently broken.

The web interface seems to have the same problem for ~a week by now. 2 requests for data seem to be made, one is for `https://simon04.dev.openstreetmap.org/whodidit/scripts/changeset.php?latest=1` with the reply expected to be JSON, but:
```
<br />
<b>Fatal error</b>:  Uncaught mysqli_sql_exception: Table './simon04/wdi_changesets' is marked as crashed and last (automatic?) repair failed in /home/simon04/whodidit_prod/scripts/changeset.php:20
Stack trace:
#0 /home/simon04/whodidit_prod/scripts/changeset.php(20): mysqli-&gt;query()
#1 {main}
  thrown in <b>/home/simon04/whodidit_prod/scripts/changeset.php</b> on line <b>20</b><br />
```
and similarly a request with the actual filter parameters against `tiles.php` also expect JSON and getting the similar:
```
<br />
<b>Fatal error</b>:  Uncaught mysqli_sql_exception: Table './simon04/wdi_tiles' is marked as crashed and last (automatic?) repair failed in /home/simon04/whodidit_prod/scripts/tiles.php:104
Stack trace:
#0 /home/simon04/whodidit_prod/scripts/tiles.php(104): mysqli-&gt;query()
#1 {main}
  thrown in <b>/home/simon04/whodidit_prod/scripts/tiles.php</b> on line <b>104</b><br />
```
Looks like the database(s) are toast, currently.

Not sure what a random user like me could do, if anything at the moment, beside wishing the maintainer(s) good health & best of luck in restoring the service!

**Comment by hungerburg** [comment]
Simon get UP! I want to see what happens! In the community forum they talk about Blockwarts, Hell yes, I am simply a wart and just interested into what my fellow companions are about and perhaps welcome newbies.

**Comment by EvansMike** [comment]
I'm running the same code at home and it works fine so I concur that the DB is broken.

**Comment by bloerwald** [comment]
!61 simplifies setting up the code at home. If you're using my fork to catch up your changes, you'll will want to

- Get docker to use the simpler setup mechanism.
- Edit `scripts/parse_osc.pl` line 38 to `my $hours_to_import_if_no_previous_state = 24 * 22;`, which should be roughly when the site went down (22 days ago).
- Edit `docker-compose.yml` line 58 to have roughly your relevant bounding box to speed things up, e.g. `         && echo "export WDI_UPDATE_BBOX='5.287054,44.131024,5.935003,45.15189'"     >> /update_wrap.sh \`. The bbox from your RSS feed will work fine. If you have multiple feeds, just take the lowest + highest values in both directions.
- Get the thing up with `wdi_password=password docker compose up --build`.
- Check in a browser whether `http://localhost:8080` works.
- Redirect your RSS feed by replacing the host there (probably you'll want to keep the original one in case it comes back online). 
- It will automatically update every hour while it is running. You can stop it and it will catch up with the changes the next time you start it.

**Comment by GITMichaelK** [comment]
I have been using this application for a long time and would appreciate, if it could be fixed.
Thank you.

**Comment by cayenne17** [comment]
Incidentally, I've found an alternative that I've been using for a while now:
https://resultmaps.neis-one.org/osm-edits-tile/

**Comment by GITMichaelK** [comment]
Thank you @cayenne17,
> https://resultmaps.neis-one.org/osm-edits-tile/

works, but is missing the bounding box, so the area is a bit to small for my area of interest.

**Comment by dex2000** [comment]
looks like it works again, but last data are from april (if i see correctly)

**Comment by GITMichaelK** [comment]
Thank you @dex2000, you are right!
For full results, I had to modify the [RSS-URL](https://simon04.dev.openstreetmap.org/whodidit/).

**Comment by aswerkljh** [comment]
> Thank you @dex2000, you are right! For full results, I had to modify the [RSS-URL](https://simon04.dev.openstreetmap.org/whodidit/).

Can you please explain what you did? The link you posted just points at the main site.

**Comment by dex2000** [comment]
here is an feed-url for example:
https://simon04.dev.openstreetmap.org/whodidit/scripts/rss.php?bbox=11.498847,50.847004,11.678748,50.964779
you can see, the last is from april

**Comment by GITMichaelK** [comment]
>>    Thank you @dex2000, you are right! For full results, I had to modify the RSS-URL.

> Can you please explain what you did? The link you posted just points at the main site.

The main site is correct, I draw "my" bonding box and pressed "Get RSS-URL".
BUT: The site as been workinf for a day or two, actually it seems to be down again.

**Comment by dex2000** [comment]
For me is it online.

**Comment by GITMichaelK** [comment]
Yes it is online all time, but as you mentioned already [here](https://github.com/simon04/whodidit/issues/60#issuecomment-2336672927), actual changes are not reported right now. This has been working for a short time during last days ...

**Comment by simon04** [comment]
The ingesting process is working again. The change from MySQL to MariaDB required an adaption, see https://github.com/simon04/whodidit/commit/7ab6dfa5d5507d7b44e4d23707cc9cdbed60fc21.
